[book]
#  This book is called
title = "Command Line Applications in Rust"
# ...but friends call it "Clair"
authors = ["The Rust CLI Working Group"]
multilingual = false
language = "en"
src = "src"

[output.html]
curly-quotes = true
additional-css = [
    "src/special-content.css",
    "theme/my-theme.css",
]
git-repository-url = "https://github.com/jaewooklee93/rust-cli"
site-url = "/book/"

# Linkcheck doesn't find images/SVG so it's not enabled for now
# [output.linkcheck]
